package tresenraya.gui;

import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import tresenraya.dao.JuegoenrayaI;
import tresenraya.dao.tresenraya;
import tresenraya.modelo.Modelotresenraya;

/**
 *
 * @author acer
 */
public class Juegotresenraya extends javax.swing.JFrame {

    private char[][] tablero;
    //implentacion
    private Juego3 jugar = new Juego3();

    /**
     * Creates new form Juegotresenraya
     */
    public Juegotresenraya() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setIconImage(new ImageIcon("logo.png").getImage());
        this.tablero = new char[3][3];
        listarResultados();
        iniciarJuego();
        //clearButtons();
        terminarJuego();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EVA_TRES = new javax.swing.JPanel();
        EVALUACIONU2 = new javax.swing.JLabel();
        tresenraya = new javax.swing.JLabel();
        Nombrejlrq = new javax.swing.JLabel();
        tablerodejugadoryresultado = new javax.swing.JPanel();
        Boton_iniciar_partida = new javax.swing.JButton();
        Boton_anular_partida = new javax.swing.JButton();
        nombrejugador1 = new javax.swing.JLabel();
        nombrejugador2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablero = new javax.swing.JTable();
        PanelGanadas = new javax.swing.JPanel();
        Jugador1 = new javax.swing.JLabel();
        Jugador2 = new javax.swing.JLabel();
        Xpartidas = new javax.swing.JLabel();
        Opartidas = new javax.swing.JLabel();
        XpartidasGanadas = new javax.swing.JLabel();
        OpartidasGanadas = new javax.swing.JLabel();
        TURNO = new javax.swing.JLabel();
        PanelTablero = new javax.swing.JPanel();
        Boton0_2 = new javax.swing.JButton();
        Boton2_0 = new javax.swing.JButton();
        Boton2_2 = new javax.swing.JButton();
        Boton1_0 = new javax.swing.JButton();
        Boton0_0 = new javax.swing.JButton();
        Boton1_2 = new javax.swing.JButton();
        Boton2_1 = new javax.swing.JButton();
        Boton1_1 = new javax.swing.JButton();
        Boton0_1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));

        EVA_TRES.setBackground(new java.awt.Color(102, 255, 102));

        EVALUACIONU2.setText("EVALUCACION UNIDAD 2");

        tresenraya.setText("TRES EN RAYA");

        Nombrejlrq.setText("NOMBRE: Jhan Logan Ramos Quispe");

        javax.swing.GroupLayout EVA_TRESLayout = new javax.swing.GroupLayout(EVA_TRES);
        EVA_TRES.setLayout(EVA_TRESLayout);
        EVA_TRESLayout.setHorizontalGroup(
            EVA_TRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EVA_TRESLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EVA_TRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EVA_TRESLayout.createSequentialGroup()
                        .addComponent(EVALUACIONU2)
                        .addGap(62, 62, 62)
                        .addComponent(tresenraya))
                    .addComponent(Nombrejlrq))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        EVA_TRESLayout.setVerticalGroup(
            EVA_TRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EVA_TRESLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EVA_TRESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EVALUACIONU2)
                    .addComponent(tresenraya))
                .addGap(27, 27, 27)
                .addComponent(Nombrejlrq)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tablerodejugadoryresultado.setBackground(new java.awt.Color(51, 204, 255));

        Boton_iniciar_partida.setText("INICIAR");
        Boton_iniciar_partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_iniciar_partidaActionPerformed(evt);
            }
        });

        Boton_anular_partida.setText("ANULAR");
        Boton_anular_partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_anular_partidaActionPerformed(evt);
            }
        });

        nombrejugador1.setText("Nombre del jugador 1:");

        nombrejugador2.setText("Nombre del jugador 2:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setText("TABLA DE PUNTAJE");

        Tablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_resultado", "nombre_partida", "nombre_jugador1", "nombre_jugador2", "ganador", "punto", "estado"
            }
        ));
        jScrollPane1.setViewportView(Tablero);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tablerodejugadoryresultadoLayout = new javax.swing.GroupLayout(tablerodejugadoryresultado);
        tablerodejugadoryresultado.setLayout(tablerodejugadoryresultadoLayout);
        tablerodejugadoryresultadoLayout.setHorizontalGroup(
            tablerodejugadoryresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablerodejugadoryresultadoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(tablerodejugadoryresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablerodejugadoryresultadoLayout.createSequentialGroup()
                        .addComponent(Boton_iniciar_partida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton_anular_partida))
                    .addGroup(tablerodejugadoryresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tablerodejugadoryresultadoLayout.createSequentialGroup()
                            .addComponent(nombrejugador2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tablerodejugadoryresultadoLayout.createSequentialGroup()
                            .addComponent(nombrejugador1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tablerodejugadoryresultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tablerodejugadoryresultadoLayout.setVerticalGroup(
            tablerodejugadoryresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablerodejugadoryresultadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(tablerodejugadoryresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrejugador1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablerodejugadoryresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrejugador2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(tablerodejugadoryresultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_iniciar_partida)
                    .addComponent(Boton_anular_partida))
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PanelGanadas.setBackground(new java.awt.Color(204, 0, 0));

        Jugador1.setText("Jugador 1:");

        Jugador2.setText("Jugador 2:");

        Xpartidas.setText("X");

        Opartidas.setText("O");

        XpartidasGanadas.setText("0");

        OpartidasGanadas.setText("0");

        TURNO.setText("TURNO ");

        javax.swing.GroupLayout PanelGanadasLayout = new javax.swing.GroupLayout(PanelGanadas);
        PanelGanadas.setLayout(PanelGanadasLayout);
        PanelGanadasLayout.setHorizontalGroup(
            PanelGanadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGanadasLayout.createSequentialGroup()
                .addGroup(PanelGanadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGanadasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelGanadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGanadasLayout.createSequentialGroup()
                                .addComponent(Jugador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Xpartidas))
                            .addGroup(PanelGanadasLayout.createSequentialGroup()
                                .addComponent(Jugador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Opartidas)))
                        .addGap(46, 46, 46)
                        .addGroup(PanelGanadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OpartidasGanadas)
                            .addComponent(XpartidasGanadas)))
                    .addGroup(PanelGanadasLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(TURNO, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        PanelGanadasLayout.setVerticalGroup(
            PanelGanadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGanadasLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(TURNO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGanadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugador1)
                    .addComponent(Xpartidas)
                    .addComponent(XpartidasGanadas))
                .addGap(29, 29, 29)
                .addGroup(PanelGanadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugador2)
                    .addComponent(Opartidas)
                    .addComponent(OpartidasGanadas))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        PanelTablero.setBackground(new java.awt.Color(51, 153, 255));

        Boton0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0_2ActionPerformed(evt);
            }
        });

        Boton2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2_0ActionPerformed(evt);
            }
        });

        Boton2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2_2ActionPerformed(evt);
            }
        });

        Boton1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1_0ActionPerformed(evt);
            }
        });

        Boton0_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0_0ActionPerformed(evt);
            }
        });

        Boton1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1_2ActionPerformed(evt);
            }
        });

        Boton2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2_1ActionPerformed(evt);
            }
        });

        Boton1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1_1ActionPerformed(evt);
            }
        });

        Boton0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTableroLayout = new javax.swing.GroupLayout(PanelTablero);
        PanelTablero.setLayout(PanelTableroLayout);
        PanelTableroLayout.setHorizontalGroup(
            PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelTableroLayout.createSequentialGroup()
                        .addComponent(Boton0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTableroLayout.createSequentialGroup()
                        .addComponent(Boton0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boton2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelTableroLayout.createSequentialGroup()
                        .addComponent(Boton1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTableroLayout.setVerticalGroup(
            PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EVA_TRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PanelGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tablerodejugadoryresultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EVA_TRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tablerodejugadoryresultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Boton0_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0_0ActionPerformed
        jugar.tiradaJugador(Boton0_0, 0, 0, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);    // TODO add your handling code here:
    }//GEN-LAST:event_Boton0_0ActionPerformed

    private void Boton0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0_1ActionPerformed
        jugar.tiradaJugador(Boton0_1, 0, 1, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton0_1ActionPerformed

    private void Boton0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0_2ActionPerformed
        jugar.tiradaJugador(Boton0_2, 0, 2, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton0_2ActionPerformed

    private void Boton1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1_0ActionPerformed
        jugar.tiradaJugador(Boton1_0, 1, 0, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1_0ActionPerformed

    private void Boton1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1_1ActionPerformed
        jugar.tiradaJugador(Boton1_1, 1, 1, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1_1ActionPerformed

    private void Boton1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1_2ActionPerformed
        jugar.tiradaJugador(Boton1_2, 1, 2, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1_2ActionPerformed

    private void Boton2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2_0ActionPerformed
        jugar.tiradaJugador(Boton2_0, 2, 0, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2_0ActionPerformed

    private void Boton2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2_1ActionPerformed
        jugar.tiradaJugador(Boton2_1, 2, 1, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2_1ActionPerformed

    private void Boton2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2_2ActionPerformed
        jugar.tiradaJugador(Boton2_2, 2, 2, tablero, XpartidasGanadas, OpartidasGanadas, PanelTablero);        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2_2ActionPerformed

    private void Boton_iniciar_partidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_iniciar_partidaActionPerformed
        jugar.iniciarPartida(PanelTablero, true, tablero);    
        listarResultados();
// TODO add your handling code here:
    }//GEN-LAST:event_Boton_iniciar_partidaActionPerformed

    private void Boton_anular_partidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_anular_partidaActionPerformed
        jugar.teminarPartida(PanelTablero, false, tablero);     // TODO add your handling code here:
    }//GEN-LAST:event_Boton_anular_partidaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juegotresenraya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juegotresenraya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juegotresenraya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juegotresenraya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juegotresenraya().setVisible(true);
            }
        });
    }

    // Inicia el juego
    public void iniciarJuego() {
        jugar.iniciarPartida(PanelTablero, false, tablero);
    }

    public void terminarJuego() {
        jugar.teminarPartida(PanelTablero, true, tablero);
    }

    // Limpia los botones
    public void clearButtons() {
        jugar.habilitarTrablero(PanelTablero, false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0_0;
    private javax.swing.JButton Boton0_1;
    private javax.swing.JButton Boton0_2;
    private javax.swing.JButton Boton1_0;
    private javax.swing.JButton Boton1_1;
    private javax.swing.JButton Boton1_2;
    private javax.swing.JButton Boton2_0;
    private javax.swing.JButton Boton2_1;
    private javax.swing.JButton Boton2_2;
    private javax.swing.JButton Boton_anular_partida;
    private javax.swing.JButton Boton_iniciar_partida;
    private javax.swing.JLabel EVALUACIONU2;
    private javax.swing.JPanel EVA_TRES;
    private javax.swing.JLabel Jugador1;
    private javax.swing.JLabel Jugador2;
    private javax.swing.JLabel Nombrejlrq;
    private javax.swing.JLabel Opartidas;
    private javax.swing.JLabel OpartidasGanadas;
    private javax.swing.JPanel PanelGanadas;
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JLabel TURNO;
    private javax.swing.JTable Tablero;
    private javax.swing.JLabel Xpartidas;
    private javax.swing.JLabel XpartidasGanadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel nombrejugador1;
    private javax.swing.JLabel nombrejugador2;
    private javax.swing.JPanel tablerodejugadoryresultado;
    private javax.swing.JLabel tresenraya;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel model;

    public void listarResultados() {
        JuegoenrayaI dao = new tresenraya();
        List<Modelotresenraya> lista = dao.listarResultado();
        model = (DefaultTableModel) Tablero.getModel();
        //System.out.println("hh:"+lista.size());
        model.setNumRows(0);
        Object[] ob = new Object[7];
        for (int i = 0; i < lista.size(); i++) {
            int x = -1;
            ob[++x] = lista.get(i).getIdresultado();
            ob[++x] = lista.get(i).getNombre_partida ();
            ob[++x] = lista.get(i).getNombre_jugador1();
            ob[++x] = lista.get(i).getNombre_jugador2();
            ob[++x] = lista.get(i).getGanador();
            ob[++x] = lista.get(i).getPunto();
            ob[++x] = lista.get(i).getEstado();
            model.addRow(ob);
        }
    }

}
